name: CI/CD Pipeline

on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        
        
      - name: Test work_DB package
        working-directory: work_DB
        run: |
          go test ./...          

      - name: Test main package
        run: |
          go test ./...

